user_num=input("Give me an integer: ")
print(user_num)
num=int(user_num)
print(num+10)
print("=====shorter way=====")
num=int(input("Give me an integer: "))
print(num+10)
# print(user_num + 10)
print("===========")
print(int("5"))
print(int(4.6))
print(int(3.1))
print(int(-45.4))
print(int("Bob"))